### ISSUE TITLE
Suggestion: split audio/video assoc

### ISSUE THREAD

**Issue by Kaens** [rossy/mpv-install#12]
Serves me right I guess, should've read the random .bat from the Internet _then_ run it as admin.
But still. I have a separate audio player I really like, so it was rather unexpected. Probably not just me.

**Comment by rossy** [comment]
Well, mpv-install doesn't create the file associations directly. Since Windows Vista, applications aren't allowed to make their own associations anymore. Instead, mpv-install registers the list of file types that mpv can handle and Windows automatically creates the associations between file types and applications. Since mpv supports audio files, they are included in the list of file types provided to Windows.

In theory, Windows should prevent one application (mpv) from taking over file associations that belong to another application (your audio player) without user intervention, but if this has happened to you, you can switch them back in the Default Programs control panel ("Default Apps" in Windows 10):

![image](https://user-images.githubusercontent.com/162837/34649197-3a1560e2-f3fe-11e7-82a6-f22b7a18ac19.png)

Recent versions of Windows 10 give you a high-level option for changing the default music player as well:

![image](https://user-images.githubusercontent.com/162837/34649254-71f8b4c2-f3ff-11e7-9786-36462a2796f0.png)

As for splitting audio and video types in the batch file itself, I don't think that's the right solution. The Windows UI should be used instead. This is why mpv-install launches the Default Programs control panel when it is finished registering the new file types.

**Comment by Kaens** [comment]
Thanks for answering so exhaustively. My system is Windows 10, yes, and it has indeed defied theory in deciding it shouldn't ask me and just quietly switch to a different default app, but that's for a different discussion.

At this time, I'm simply curious as to exactly why you don't think the more user-friendly solution is the right one here. Of course Windows UI should be used for tweaking and fine-tuning. But is there any objective need to force people to go tweaking in the first place, instead of having them run a relevant amount of batch files?

I guess it's a UX issue more than anything.

**Comment by rossy** [comment]
I don't think handling it in mpv-install.bat would be a more user-friendly solution. Consistency is best, so mpv-install.bat, like all other programs, should follow Microsoft's current recommendations and make the Windows UI the only way of choosing which set of file types are associated with a certain program. Split batch files would make the process more complicated for the user, because they would still have to use the Windows UI for their final selection, but they would also have to make sure they ran the relevant set of batch files first.
