### ISSUE TITLE
How on earth do "Default programs" work?

### ISSUE THREAD

**Issue by ondras** [rossy/mpv-install#4]
This is actually not a bug report.

I copied most of this project's `mpv-install.bat` into my own project, which is a music (only) player. But for some strange reason, after executing the modified batch file, my player still does not apper in the _Default programs_ listing.

My batch is here: https://github.com/ondras/mp/blob/gh-pages/bin/reg.bat

Everything else works -- extension association, _Open with..._ item, verbs, icons. Just the program itself is apparently not registered properly.

Perhaps the reason for this is that my program is not an executable, but rather a `mp.bat` run-script (https://github.com/ondras/mp/blob/gh-pages/bin/mp.bat)? Are only .exe files allowed in the _Default programs_ listing?

I am also not exactly sure how the RegisteredApplications -> Capabilities linking works, because the Capabilities registry key does not reference the binary itself; instead, it only lists the programs' ProgIds. Where do the program Icon, Company, Website (these are shown in the _Default programs_) come from?

Thanks for any insights into this. Or a suggestion how to debug this weird stuff.

**Comment by ondras** [comment]
(updated path to my batch file to https://github.com/ondras/mp/blob/gh-pages/bin/install.bat)

**Comment by rossy** [comment]
> Perhaps the reason for this is that my program is not an executable, but rather a mp.bat run-script (https://github.com/ondras/mp/blob/gh-pages/bin/mp.bat)? Are only .exe files allowed in the Default programs listing?

Yeah, it's possible. That would be my first guess. Your batch file looks right and if file associations work, that means the ProgIds are registered correctly.

> I am also not exactly sure how the RegisteredApplications -> Capabilities linking works, because the Capabilities registry key does not reference the binary itself; instead, it only lists the programs' ProgIds. Where do the program Icon, Company, Website (these are shown in the Default programs) come from?

Apparently the Default Programs UI gets metadata from the handler for the first ProgId it finds, so that's probably where this data comes from. The website URL only appears for digitally signed programs and comes from the certificate.

If the Default Programs UI expects the first ProgId to point to an executable so it can extract this data, that might explain why it doesn't work with associations that are created against a batch file.

If you haven't read it already, this article might be useful: https://msdn.microsoft.com/en-us/library/windows/desktop/cc144154.aspx

**Comment by ondras** [comment]
Thanks for your answer! :+1:
