### ISSUE TITLE
No closing quote in command value

### ISSUE THREAD

**Issue by hashn0n** [rossy/mpv-install#5]
So, after using mpv-install.bat and checking regedit to see how mpv.exe is invoked I see something like that:
`"B:\blah\blah\mpv.exe"  -- "%L`
Take a note that there is no closing quote!
Is that as intended or not I do not know but if it isn't some one need to run a string replace like this:
From `\"%%%%L"`
To `\"%%%%L\""`

**Comment by rossy** [comment]
Yep, this is intended. It was added in 934c171 to fix DVD autoplay by exploiting a quirk of the MSVCRT command line parser. I don't think it's technically needed for the normal file associations, but it's harmless, so it's used there as well for consistency's sake.

Basically, if the command-line argument is fully quoted like `"C:\mpv\mpv.exe" dvd:// --dvd-device="%L"` and you play a DVD from `D:\`, the shell will substitute the DVD drive in like `"C:\mpv\mpv.exe" dvd:// --dvd-device="D:\"`. Because `\"` is the syntax for escaping a quote, an MSVCRT program will see `--dvd-device=D:"` in argv[2] and the DVD will not play. This can be avoided by only using an opening quote with no closing quote, in which case the last command line argument will continue to the end of the command line. Since file paths in Windows can't contain the quote character, it will work for all paths, including paths that end with a backslash.

For some reason, Microsoft's own programs don't need this. Windows Media Player has a DVD play command like `"%ProgramFiles(x86)%\Windows Media Player\wmplayer.exe" /prefetch:4 /device:DVD "%L"` and that seems to just work. They probably use a custom command line parser.
